module.exports = {
  DAMAGE_PERCENTAGE: 0.3,
  DEFAULT_USER_INDICATOR: '>>>>',
  NOT_AVAILABLE_SPACE: '~',
  STARTING_POINT: 'X',
  EXIT_FORWARD: '>',
  EXIT_BACKWARD: '<',
  VERTICAL_WALL: '║',
  HORIZONTAL_WALL: '═',
  TOP_LEFT_WALL: '╔',
  TOP_RIGHT_WALL: '╗',
  BOTTOM_RIGHT_WALL: '╝',
  BOTTOM_LEFT_WALL: '╚',
  ELF: '🧝',
  MONSTER: '👹',
  WOMAN: '👩',

  COLORS: {
    RESET: '\x1b[0m',
    RED: '\x1b[31m',
    GREEN: '\x1b[32m',
    YELLOW: '\x1b[33m',
    BLUE: '\x1b[34m',
    MAGENTA: '\x1b[35m',
    CYAN: '\x1b[36m',
    WHITE: '\x1b[37m',
    BOLD: '\x1b[1m',
  },
}
