module.exports = {
  DAMAGE_PERCENTAGE: 0.3,
  DEFAULT_USER_INDICATOR: '>>>>',
  VERTICAL_WALL: '║',
  HORIZONTAL_WALL: '═',
  TOP_LEFT_WALL: '╔',
  TOP_RIGHT_WALL: '╗',
  BOTTOM_RIGHT_WALL: '╝',
  BOTTOM_LEFT_WALL: '╚',
}